clothing = Spree::TaxCategory.find_by_name!("Clothing")
shipping_category = Spree::ShippingCategory.find_by_name!("Default")

default_attrs = {
  :description => Faker::Lorem.paragraph,
  :available_on => Time.zone.now
}

products = [
  {
    :name => "1 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 25.59,
  },
  {
    :name => "2 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 22.79,
  },
  {
    :name => "3 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.49,
  },
    {
    :name => "4 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.99,
  },
    {
    :name => "5 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.99,
  },
    {
    :name => "6 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 21.59,
  },
    {
    :name => "7 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.79,
  },
    {
    :name => "8 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "9 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 22.39,
  },
    {
    :name => "10 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
    {
    :name => "11 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 22.49,
  },
    {
    :name => "12 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "13 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "14 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "15 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "16 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.69,
  },
    {
    :name => "17 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.39,
  },
    {
    :name => "18 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.99,
  },
    {
    :name => "19 Earings",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 29.29,
  },
    {
    :name => "1 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.39,
  },
      {
    :name => "2 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.39,
  },
      {
    :name => "3 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.09,
  },
      {
    :name => "4 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.09,
  },
      {
    :name => "5 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.09,
  },
      {
    :name => "6 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.09,
  },
      {
    :name => "7 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 22.59,
  },
      {
    :name => "8 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 22.59,
  },
      {
    :name => "9 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 33.29,
  },
      {
    :name => "10 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 20.29,
  },
      {
    :name => "11 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 20.29,
  },
      {
    :name => "12 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 19.69,
  },
      {
    :name => "13 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 20.09,
  },
      {
    :name => "14 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 19.99,
  },
      {
    :name => "15 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.69,
  },
      {
    :name => "16 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.69,
  },
      {
    :name => "17 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.99,
  },
      {
    :name => "18 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 28.29,
  },
      {
    :name => "19 Necklace",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 28.29,
  },
      {
    :name => "1 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.49,
  },
       {
    :name => "2 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.49,
  },
       {
    :name => "3 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "4 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "5 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "6 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "7 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.89,
  },
       {
    :name => "8 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "9 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
       {
    :name => "10 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.99,
  },
       {
    :name => "11 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.79,
  },
       {
    :name => "12 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 26.89,
  },
       {
    :name => "13 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.79,
  },
       {
    :name => "14 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.79,
  },
       {
    :name => "15 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 19.99,
  },
       {
    :name => "16 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.69,
  },
         {
    :name => "17 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 27.69,
  },
       
       {
    :name => "18 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 28.59,
  },
       {
    :name => "19 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.59,
  },
       {
    :name => "20 Bracelet",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 23.89,
  },
     {
    :name => "1 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 29.79,
  },
       {
    :name => "2 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 20.49,
  },
       {
    :name => "3 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 26.79,
  },
       {
    :name => "4 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 25.29,
  },
       {
    :name => "5 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.99,
  },
       {
    :name => "6 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.99,
  },
       {
    :name => "7 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.99,
  },
       {
    :name => "8 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 15.79,
  },
       {
    :name => "9 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 16.09,
  },
       {
    :name => "10 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 25.89,
  },
       {
    :name => "11 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 29.09,
  },
       {
    :name => "12 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.69,
  },
       {
    :name => "13 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.69,
  },
       {
    :name => "14 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 30.69,
  },
       {
    :name => "15 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 29.09,
  },
       {
    :name => "16 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.29,
  },
       {
    :name => "17 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.29,
  },
       {
    :name => "18 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 24.29,
  },
       {
    :name => "19 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 26.09,
  },
       {
    :name => "20 Scarf",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 29.79,
  },
     {
    :name => "1 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 54.19,
  },
       {
    :name => "2 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 105.09,
  },
       {
    :name => "3 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 51.79,
  },
       {
    :name => "4 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 67.79,
  },
       {
    :name => "5 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 59.09,
  },
       {
    :name => "6 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 81.79,
  },
       {
    :name => "7 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 66.69,
  },
       {
    :name => "8 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 44.59,
  },
       {
    :name => "9 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 36.79,
  },
       {
    :name => "10 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 32.59,
  },
       {
    :name => "11 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 32.59,
  },
       {
    :name => "12 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 47.39,
  },
       {
    :name => "13 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 75.29,
  },
       {
    :name => "14 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 42.79,
  },
       {
    :name => "15 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 67.79,
  },
       {
    :name => "16 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 65.29,
  },
       {
    :name => "17 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 50.29,
  },
       {
    :name => "18 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 51.69,
  },
       {
    :name => "19 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 65.89,
  },
       {
    :name => "20 Bag",
    :tax_category => clothing,
    :shipping_category => shipping_category,
    :price => 43.19,
  },
]

products.each do |product_attrs|
  Spree::Config[:currency] = "USD"

  default_shipping_category = Spree::ShippingCategory.find_by_name!("Default")
  product = Spree::Product.create!(default_attrs.merge(product_attrs))
  product.shipping_category = default_shipping_category
  product.save!
end

Spree::Config[:currency] = "USD"